---
title: "Questions for Lab 1, 2 and 3"
author: "Leo lahti & Rajesh Shigdel"
date: "`r Sys.Date()`"
output: html_document
---

# Tutorial Aims 
In this tutorial we will learn feature selection, dimension reduction, clustering, visualization, analysis and interpretation  using  
 miaverse (mia = MIcrobiome Analysis) and miaViz - (Microbiome Analysis Plotting and Visualization) to explore patterns in human gut microbiome datasets. 

The examples in this tutorial are mainly based on this online book        
[Orchestrating Microbiome Analysis](https://microbiome.github.io/OMA/)

In this tutorial we use data from [The Human Gut Microbiome Atlas (HGMA)](https://www.microbiomeatlas.org/)



# Lab 1 
   
   
## unsupervised learning: Feature selection & dimension reduction
   
1. Make the tse (TreeSummarizedExperiment) Object for the further analysis (use the provided script to make a tse )

## Load the data 


2. Aggregate the data to Phylum level (agglomerateByRank)


3. Subset the data at the Species level with only taking bacterial Species that are greater than 10% of prevalence in the total sample


4. Subset a tse object which consist only two phyla i.e Actinobacteria", "Cyanobacteria

 
5. Calculate relative abundances, and store the table to assays


6.Perform a centred log-ratio transformation (clr) (i.e. mia::transformSamples)



# Lab 2 
       
  
## unsupervised learning: clustering & visualization
                   
 1. Visualize beta diversity using principal coordinate analysis (PCoA);based on the Bray-Curtis dissimilarities


 2. Visualize beta diversity using principal coordinates analysis (PCoA); with Aitchison distance (clr transformation+ Euclidean distance)


 3. Cluster the samples using Dirichlet- multinomial mixture model 


 4. Visualize the clusters in the PCoA plot



# Lab 3 
         
                
## unsupervised learning:Analysis and interpretation 

 1. What taxa are driving the axis? Calculate the Spearman correlation between PC1 and the relative abundance of the bacteria and visualize the results in a     bar plot.


 2. Visualize the dominant taxonomic group of each sample by colour on PCoA plot 

 3. Visualize gender by colour on PCoA plot 




